import { Lexend_Deca } from "next/font/google";
import "./globals.css";
import PrivateLayout from "@/components/Layout/private";
import { Providers } from "./providers";

const lexendDeca = Lexend_Deca({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="bumblebee">
      <body className={lexendDeca.className}>
        <Providers>
          <PrivateLayout>{children}</PrivateLayout>
        </Providers>
      </body>
    </html>
  );
}
